#!/usr/bin/env node
// Zero-dependency token builder: tokens/src/*.json (W3C Design Tokens format)
// -> tokens/build/tokens.css (CSS custom properties consumed by index.html).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const srcDir = join(root, 'tokens/src');
const outDir = join(root, 'tokens/build');
const outFile = join(outDir, 'tokens.css');

const readJson = (name) => JSON.parse(readFileSync(join(srcDir, name), 'utf8'));

const spacing = readJson('spacing.json');
const radius = readJson('radius.json');
const motion = readJson('motion.json');
const layout = readJson('layout.json');
const density = readJson('density.json');

// Resolves DTCG alias refs like "{spacing.4}" against the spacing token group,
// producing a CSS var() reference so density values stay in sync with spacing.
function resolveValue(raw) {
  const m = /^\{spacing\.(.+)\}$/.exec(raw);
  if (!m) return raw;
  if (!(m[1] in spacing)) throw new Error(`Unknown spacing alias: ${raw}`);
  return `var(--sp-${m[1]})`;
}

const rootDecls = [];
rootDecls.push(`--font-sans:${layout.font.sans.$value}`);
rootDecls.push(`--font-mono:${layout.font.mono.$value}`);
for (const [key, token] of Object.entries(spacing)) rootDecls.push(`--sp-${key}:${token.$value}`);
for (const [key, token] of Object.entries(radius)) rootDecls.push(`--radius-${key}:${token.$value}`);
for (const [key, token] of Object.entries(motion.duration)) rootDecls.push(`--dur-${key}:${token.$value}`);
for (const [key, token] of Object.entries(motion.easing)) rootDecls.push(`--ease-${key}:${token.$value}`);
for (const [key, token] of Object.entries(layout.dimension)) rootDecls.push(`--${key}:${token.$value}`);

const densityBlocks = Object.entries(density).map(([mode, tokens]) => {
  const decls = Object.entries(tokens).map(([key, token]) => `--${key}:${resolveValue(token.$value)}`);
  return `html[data-density="${mode}"]{${decls.join(';')}}`;
});

const css = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
   Edit tokens/src/*.json instead, then run: node scripts/build-tokens.mjs */
:root{
  ${rootDecls.join(';\n  ')};
}
${densityBlocks.join('\n')}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, css);
console.log(`Wrote ${outFile}`);
